### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by natethegrreat** [NectarJS/nectarjs#38]
C:\Users\PC\Documents\dev code\Editor\sc>nectar test.js
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\extern\adm-zip\adm-zip.js:273:38
    at Array.forEach (<anonymous>)
    at Object.addLocalFolder (C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\extern\adm-zip\adm-zip.js:269:12)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\nectar.js:499:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

C:\Users\PC\Documents\dev code\Editor\sc>nectar test.js
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\extern\adm-zip\adm-zip.js:273:38
    at Array.forEach (<anonymous>)
    at Object.addLocalFolder (C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\extern\adm-zip\adm-zip.js:269:12)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\nectar.js:499:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

C:\Users\PC\Documents\dev code\Editor\sc>nectar test.js
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

I got this error 
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\extern\adm-zip\adm-zip.js:273:38
    at Array.forEach (<anonymous>)
    at Object.addLocalFolder (C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\extern\adm-zip\adm-zip.js:269:12)
    at C:\Users\PC\AppData\Roaming\npm\node_modules\nectarjs\nectar.js:499:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by adrien-thierry** [comment]
Did you install NectarJS with snap ?
