### ISSUE TITLE
limitation of loop by number?

### ISSUE THREAD

**Issue by hikarine3** [NectarJS/nectarjs#68]
```
for(let i=0;i<100000;i++){
	console.log("a");
}
```

Result of above code is
```
node b.js|wc
  100000  100000  200000
```

But in the case of nectar
```
 ./b |wc
   83328   83328  166656
```
on Mac OS 10.14.6.

Something is wrong about how to deal with loop's number, I think.

**Comment by adrien-thierry** [comment]
hi @hikarine3 , thank you for the bug reporting,
It's a problem with String management, I will solve it,

Try this code : 

```
for(let i=0;i<100000;i++){
	console.log(1);
}
```
Result:
```
loop.exe |wc
 100000  100000  200000
```

**Comment by adrien-thierry** [comment]
It should be corrected, can you try again ?

For benchmark or speed purpose, you can use the `--preset speed` flag

**Comment by hikarine3** [comment]
same code
```
for(let i=0;i<100000;i++){
	console.log("a");
}
```
 but I encountered error this time.

```
nectar  --version
NectarJS v0.5.27
```

```
nectar b.js 
[*] Generating source file
[*] Compiling
```

```
time deno ./b|wc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', cli/compilers/js.rs:15:13
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: std::future::poll_with_tls_context
  10: std::future::poll_with_tls_context
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
  13: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
  14: <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next
  15: <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next
  16: std::future::poll_with_tls_context
  17: <std::future::GenFuture<T> as core::future::future::Future>::poll
  18: <std::future::GenFuture<T> as core::future::future::Future>::poll
  19: std::thread::local::LocalKey<T>::with
  20: tokio::macros::scoped_tls::ScopedKey<T>::set
  21: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  22: tokio::runtime::context::enter
  23: deno::tokio_util::run_basic
  24: deno::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
       0       0       0
```

**Comment by hikarine3** [comment]
In the case of
```
nectar  --version
NectarJS v0.5.27
```
result is same
```
time ./b|wc
   83325   83325  166650
```
but is it correct version which I should retry?

**Comment by adrien-thierry** [comment]
Sorry i only pushed the code on github, i will publish the update on npm soon

**Comment by adrien-thierry** [comment]
The update is published on NPM, could you try again ?

**Comment by hikarine3** [comment]
As result, it is resolved, thanks!

In terms of the speed, speed is almost same with node.js with --preset speed flag.
########
time node b.js|wc
  100000  100000  200000

real	0m0.737s
user	0m0.757s
sys	0m0.379s
########
time deno b.js|wc
  100000  100000  200000

real	0m0.348s
user	0m0.221s
sys	0m0.255s
########
nectar --preset speed b.js;
time ./b|wc

real	0m0.747s
user	0m0.620s
sys	0m0.384s

**Comment by hikarine3** [comment]
Oh, but in the following case, the result is still but as output.
```
for(let i=0;i<100000;i++){
	for(let y=0;y<10;y++){
		console.log("a");
	}
}

```
HajimenoMacBook-ea:tmp hajimekurita$ time node c.js|wc
 1000000 1000000 2000000

real	0m4.815s
user	0m4.803s
sys	0m3.216s
HajimenoMacBook-ea:tmp hajimekurita$ time deno c.js|wc
 1000000 1000000 2000000

real	0m2.582s
user	0m1.540s
sys	0m2.370s
HajimenoMacBook-ea:tmp hajimekurita$ nectar --preset speed c.js;time ./c|wc
[*] Generating source file
[*] Compiling
      10      10      20

real	0m0.009s
user	0m0.006s
sys	0m0.005s
```

**Comment by adrien-thierry** [comment]
It's the body parser of the loop, i will correct it

**Comment by adrien-thierry** [comment]
commit 7242a5c should correct it

**Comment by hikarine3** [comment]
Error happened when compiling
```
console.log("B");
````

```
nectar --version; nectar  a.js;time ./a|wc
NectarJS v0.5.31
[*] Generating source file
[*] Compiling
In file included from /Users/hajimekurita/tmp/.nectar/ssfna/a.cpp:42:
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:788:62: error: no matching constructor for initialization of '__NJS_Class_String'
                REGISTER[_array.get().a->__NJS_VALUE[_index]._ptr].s = new __NJS_Class_String(REGISTER[_value._ptr].s->__NJS_VALUE.c_str());
                                                                           ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:73:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to 'const __NJS_Class_String' for 1st argument
class __NJS_Class_String : public __NJS_Class_Object
      ^
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:73:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to '__NJS_Class_String' for 1st argument
class __NJS_Class_String : public __NJS_Class_Object
      ^
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:77:5: note: candidate constructor not viable: 1st argument ('const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *')) would lose const qualifier
    __NJS_Class_String(char* _str);
    ^
1 error generated.
[!] Compilation error
Error: Command failed: g++ -std=c++11 /Users/hajimekurita/tmp/.nectar/ssfna/a.cpp -O1 -fpermissive -w -s   -o /Users/hajimekurita/tmp/a
In file included from /Users/hajimekurita/tmp/.nectar/ssfna/a.cpp:42:
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:788:62: error: no matching constructor for initialization of '__NJS_Class_String'
                REGISTER[_array.get().a->__NJS_VALUE[_index]._ptr].s = new __NJS_Class_String(REGISTER[_value._ptr].s->__NJS_VALUE.c_str());
                                                                           ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:73:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to 'const __NJS_Class_String' for 1st argument
class __NJS_Class_String : public __NJS_Class_Object
      ^
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:73:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to '__NJS_Class_String' for 1st argument
class __NJS_Class_String : public __NJS_Class_Object
      ^
/Users/hajimekurita/tmp/.nectar/ssfna/njs.h:77:5: note: candidate constructor not viable: 1st argument ('const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *')) would lose const qualifier
    __NJS_Class_String(char* _str);
    ^
1 error generated.

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Compiler.Compile (/Users/hajimekurita/.nodebrew/node/v12.4.0/lib/node_modules/nectarjs/compiler/native/compiler.js:394:3)
    at /Users/hajimekurita/.nodebrew/node/v12.4.0/lib/node_modules/nectarjs/nectar.js:336:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 49 6e 20 66 69 6c 65 20 69 6e 63 6c 75 64 65 64 20 66 72 6f 6d 20 2f 55 73 65 72 73 2f 68 61 6a 69 6d 65 6b 75 72 69 74 61 2f 74 6d 70 2f 2e 6e 65 63 ... 1510 more bytes>
  ],
  pid: 83126,
  stdout: <Buffer >,
  stderr: <Buffer 49 6e 20 66 69 6c 65 20 69 6e 63 6c 75 64 65 64 20 66 72 6f 6d 20 2f 55 73 65 72 73 2f 68 61 6a 69 6d 65 6b 75 72 69 74 61 2f 74 6d 70 2f 2e 6e 65 63 ... 1510 more bytes>
}
       1       1       2

real	0m0.005s
user	0m0.002s
sys	0m0.004s
```

**Comment by adrien-thierry** [comment]
It's a Clang error, i will check it

**Comment by adrien-thierry** [comment]
Related to #66

**Comment by adrien-thierry** [comment]
I reverted the string mgmt, i will update it to support more iteration as the fix i pushed was not supported by clang

**Comment by hikarine3** [comment]
At least compilation, it becomes O.K.

Multi tier lopp has still problem.
Reporting is just recording purpose though you know it.
```
cat c.js;nectar --version; nectar  c.js;time ./c|wc
for(let i=0;i<100000;i++){
	for(let y=0;y<10;y++){
		console.log("a");
	}
}
NectarJS v0.5.32
[*] Generating source file
[*] Compiling
  124993  124993  249986

real	0m1.240s
user	0m1.066s
sys	0m0.527s
```

**Comment by adrien-thierry** [comment]
thank you very much, i found the issue and corrected it, i will push the update soon

**Comment by adrien-thierry** [comment]
2c7eccf shoud solve the problem, can you give me your feedback ?

**Comment by hikarine3** [comment]
Hi, thanks for your fixing.

Here is the test result.

1) Loop problem was solved
2) But in more tests for loop, I found problem of how to deal with large number. <= Test case 4)

Please confirm.
Thanks!

========
1) OK: just console.log
```
FILE=a.js;cat $FILE;time node $FILE|md5;time deno $FILE|md5;nectar --version;nectar --preset speed $FILE;time ./a|md5
console.log("B");

30cf3d7d133b08543cb6c8933c29dfd7

real	0m0.072s
user	0m0.051s
sys	0m0.020s
30cf3d7d133b08543cb6c8933c29dfd7

real	0m0.038s
user	0m0.020s
sys	0m0.013s
NectarJS v0.5.33
[*] Generating source file
[*] Compiling
30cf3d7d133b08543cb6c8933c29dfd7

real	0m0.006s
user	0m0.003s
sys	0m0.004s
```

2) OK: Simple loop
```
 FILE=b.js;cat $FILE;time node $FILE|md5;time deno $FILE|md5;nectar --version;nectar --preset speed $FILE;time ./b|md5
for(let i=0;i<100000;i++){
		console.log("a");
}
484c67d5c84f5d502bf56e01a51066df

real	0m0.663s
user	0m0.699s
sys	0m0.374s
484c67d5c84f5d502bf56e01a51066df

real	0m0.307s
user	0m0.187s
sys	0m0.227s
NectarJS v0.5.33
[*] Generating source file
[*] Compiling
484c67d5c84f5d502bf56e01a51066df

real	0m1.090s
user	0m0.978s
sys	0m0.417s
```

3) OK: Tier 2 loop
```
FILE=c.js;cat $FILE;time node $FILE|md5;time deno $FILE|md5;nectar --version;nectar --preset speed $FILE;time ./c|md5
for(let i=0;i<100000;i++){
	for(let y=0;y<10;y++){
		console.log("a");
	}
}
050cf373c7c785c764c02e6649e6082e

real	0m5.510s
user	0m5.162s
sys	0m3.215s
050cf373c7c785c764c02e6649e6082e

real	0m2.815s
user	0m1.579s
sys	0m2.027s
NectarJS v0.5.33
[*] Generating source file
[*] Compiling
050cf373c7c785c764c02e6649e6082e

real	0m11.372s
user	0m9.789s
sys	0m4.225s
```


4) Bad: With more nest & output number
```
FILE=e.js;cat $FILE;time node $FILE|md5;time deno $FILE|md5;nectar --version;nectar --preset speed $FILE;time ./e|md5
let num = 0;
for(let i=0;i<10;i++){
	num = i+1;	
	for(let y=0;y<10;y++) {
		num *= (y+1);
		let x = 1;
		while(x<10){
			num *= (x+1);
			console.log(num);
			x++;
		}
	}
}
d6bf1ec4936f9065b4f4a8e14be3e4ce

real	0m0.091s
user	0m0.071s
sys	0m0.023s
d6bf1ec4936f9065b4f4a8e14be3e4ce

real	0m0.118s
user	0m0.030s
sys	0m0.029s
NectarJS v0.5.33
[*] Generating source file
[*] Compiling
7988b05781f6502c9bf5684bcf28de11

real	0m0.010s
user	0m0.006s
sys	0m0.008s
```

**Comment by adrien-thierry** [comment]
Thank you for your feedback,

i will add a big number lib for managing big number, could you open a new issue for this ?

**Comment by hikarine3** [comment]
I created new issue
https://github.com/NectarJS/nectarjs/issues/81

For this loop issue, I can say the problem was resolved.

Thanks for you work!
