### ISSUE TITLE
Fail to compole with size preset

### ISSUE THREAD

**Issue by CHNB128** [NectarJS/nectarjs#84]
## Env
```
➜ uname -a                                                   
Linux gnome 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux
➜ nectar --version
NectarJS v0.6.48
➜ npm --version            
6.14.5
➜ yarn --version          
1.22.4
➜ node --version
v14.3.0
```
## Source 
```
➜ cat test.js 
console.log("hi");
```
## Output 
```
➜ nectar --preset size test.js
[*] Generating source file
[*] Compiling
In file included from /home/gnome/tmp/.nectar/mx5vv/test.cpp:49:
/home/gnome/tmp/.nectar/mx5vv/lib/json.h: In function ‘int to_int(const char*)’:
/home/gnome/tmp/.nectar/mx5vv/lib/json.h:6:66: error: exception handling disabled, use ‘-fexceptions’ to enable
    6 |         throw std::invalid_argument("null or empty JSON argument");
      |                                                                  ^
[!] Compilation error
Error: Command failed: g++  -std=c++11 /home/gnome/tmp/.nectar/mx5vv/test.cpp -Os -fno-exceptions -fno-rtti -fno-stack-protector -fomit-frame-pointer -fpermissive -w -s   -o /home/gnome/tmp/test
In file included from /home/gnome/tmp/.nectar/mx5vv/test.cpp:49:
/home/gnome/tmp/.nectar/mx5vv/lib/json.h: In function ‘int to_int(const char*)’:
/home/gnome/tmp/.nectar/mx5vv/lib/json.h:6:66: error: exception handling disabled, use ‘-fexceptions’ to enable
    6 |         throw std::invalid_argument("null or empty JSON argument");
      |                                                                  ^

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at Compiler.Compile (/home/gnome/.local/share/yarn/global/node_modules/nectarjs/compiler/native/compiler.js:568:3)
    at /home/gnome/.local/share/yarn/global/node_modules/nectarjs/nectar.js:485:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 49 6e 20 66 69 6c 65 20 69 6e 63 6c 75 64 65 64 20 66 72 6f 6d 20 2f 68 6f 6d 65 2f 67 6e 6f 6d 65 2f 74 6d 70 2f 2e 6e 65 63 74 61 72 2f 6d 78 35 76 ... 367 more bytes>
  ],
  pid: 107876,
  stdout: <Buffer >,
  stderr: <Buffer 49 6e 20 66 69 6c 65 20 69 6e 63 6c 75 64 65 64 20 66 72 6f 6d 20 2f 68 6f 6d 65 2f 67 6e 6f 6d 65 2f 74 6d 70 2f 2e 6e 65 63 74 61 72 2f 6d 78 35 76 ... 367 more bytes>
}
```

**Comment by adrien-thierry** [comment]
Hi @CHNB128 ,

Thank you for submitting the issue, it should be corrected with dbf7ac8

**Comment by CHNB128** [comment]
Cool, thanks!

**Comment by adrien-thierry** [comment]
Could you try and tell me if it solves the problem ?

**Comment by CHNB128** [comment]
Sure. I little busy now, but I will ping you toady about it.

**Comment by adrien-thierry** [comment]
Thank you

**Comment by CHNB128** [comment]
Ok. All good on this one. 
Thanks a lot! :+1:
